name: Update Toffee
on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘণ্টায় আপডেট হবে
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run script
        run: python toffee.py
      - name: Push update
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add toffee.m3u
          git commit -m "Auto Update" || exit 0
          git push
